spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:2025/user_service_db
    username: postgres
    password: 2025
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use 'update' for development. Use 'none' or Liquibase for production.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
jwt:
  secret: Anass-secret-key-is-very-long-and-secure-key
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/

debug: true