spring:
  application:
    name: service-registry
  datasource:
    url: jdbc:postgresql://localhost:2025/eurekaservice_db
    username: postgres
    password: 2025
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: 8765

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false

