spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: reservation-all
          uri: lb://reservation-service
          predicates:
            - Path=/reservation-service/all
          filters:
            - SetPath=/api/v1/reservation/all

        - id: reservation-get
          uri: lb://reservation-service
          predicates:
            - Path=/reservation-service/get/**
          filters:
            - RewritePath=/reservation-service/get/(?<segment>.*), /api/v1/reservation/get/${segment}

server:
  port: 8766

logging:
  level:
    org.springframework:
      web: DEBUG
      security: DEBUG
      cloud.gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    preferIpAddress: false
